// HERE  I HAVE USED THE NEW Gemini models API KEY TO FETCH THE CONTENT FROM IT USING ITS API...
require('dotenv').config();
const { GoogleGenerativeAI } = require("@google/generative-ai");


const genAI = new GoogleGenerativeAI(process.env.API_KEY);

async function run() {
  const model = genAI.getGenerativeModel({ model: "gemini-pro" });
  const prompt = "Write push method do in array?";//   user prompt...

  try {
    const result = await model.generateContent(prompt); // result generated by the model
    const response = await result.response;
    const text = response.text();
    console.log(text);// console the text fetch from the model here...
  } catch (error) {
    console.error('Error:', error.message);
  }
}

run();
